"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from corsheaders.defaults import default_headers
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

SECRET_KEY = config("SECRET_KEY", default="secret")

DEBUG = config("DEBUG", default=True, cast=bool)

PRODUCTION = config("PRODUCTION", default=True, cast=bool)

ALLOWED_HOSTS = ["*"]

DEFAULT_HTTP_PROTOCOL = "http"

SPECTACULAR_SETTINGS = {
    "TITLE": "P2V API",
    "DESCRIPTION": "API do P2V",
    "VERSION": "1.0.0",
    "SERVE_PERMISSIONS": ["rest_framework.permissions.IsAdminUser"],
}

# Application definition
DATA_UPLOAD_MAX_NUMBER_FIELDS = 6000

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# Configuração opcional para permitir todos os métodos HTTP
CORS_ALLOW_ALL_METHODS = True

# Configuração opcional para permitir todos os cabeçalhos HTTP
CORS_ALLOW_ALL_HEADERS = True

# Configuração opcional para permitir credenciais (cookies, cabeçalhos de autorização) através do CORS
CORS_ALLOW_CREDENTIALS = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly",
    ],
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

IS_TESTING = len(sys.argv) > 1 and sys.argv[1] == "test"

# Django Debug Toolbar settings
if DEBUG and not IS_TESTING:
    INSTALLED_APPS += ["debug_toolbar"]
    MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]

    DEBUG_TOOLBAR_CONFIG = {
        "SHOW_TOOLBAR_CALLBACK": lambda request: True,
    }

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


if PRODUCTION:
    CLOUDFRONT_DOMAIN = config("CLOUDFRONT_DOMAIN")
    AWS_ACCESS_KEY_ID = os.environ.get("aws_access_key_id") or config(
        "aws_access_key_id", default=None
    )
    AWS_SECRET_ACCESS_KEY = os.environ.get("aws_secret_access_key") or config(
        "aws_secret_access_key", default=None
    )
    AWS_SESSION_TOKEN = os.environ.get("aws_session_token") or config(
        "aws_session_token", default=None
    )

    AWS_STORAGE_BUCKET_NAME = "p2v-media"
    AWS_S3_REGION_NAME = "sa-east-1"
    AWS_QUERYSTRING_EXPIRE = 604800
    AWS_S3_CUSTOM_DOMAIN = f"{CLOUDFRONT_DOMAIN}"

    STATIC_URL = f"https://{CLOUDFRONT_DOMAIN}/static/"
    STATIC_LOCATION = "static"

    MEDIA_URL = f"https://{CLOUDFRONT_DOMAIN}/media/"
    PUBLIC_MEDIA_LOCATION = "media"

    STORAGES = {
        "staticfiles": {"BACKEND": "core.storage_backends.StaticStorage"},
        "default": {"BACKEND": "core.storage_backends.MediaStorage"},
    }
else:
    STATIC_URL = "static/"
    STATIC_ROOT = BASE_DIR / "static"

    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    MEDIA_URL = "/media/"
    DBBACKUP_STORAGE = "django.core.files.storage.FileSystemStorage"
    DBBACKUP_STORAGE_OPTIONS = {"location": "/backup/"}
